name: Run Discord Bot (Conda)

on:
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 330
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          channels: conda-forge
          channel-priority: strict
          auto-activate-base: false
          conda-remove-defaults: true

      - name: Create env
        shell: bash -l {0}
        run: |
          conda env create -f environment.yml

      - name: Run bot
        shell: bash -l {0}
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          conda activate discordbot
          python bot.py
